<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kaamelott.proto

namespace Kaamelott;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kaamelott.QuoteInfos</code>
 */
class QuoteInfos extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string episode = 10;</code>
     */
    protected $episode = '';
    /**
     * Generated from protobuf field <code>string season = 20;</code>
     */
    protected $season = '';
    /**
     * Generated from protobuf field <code>string character = 40;</code>
     */
    protected $character = '';
    /**
     * Generated from protobuf field <code>string actor = 50;</code>
     */
    protected $actor = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $episode
     *     @type string $season
     *     @type string $character
     *     @type string $actor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kaamelott::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string episode = 10;</code>
     * @return string
     */
    public function getEpisode()
    {
        return $this->episode;
    }

    /**
     * Generated from protobuf field <code>string episode = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEpisode($var)
    {
        GPBUtil::checkString($var, True);
        $this->episode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string season = 20;</code>
     * @return string
     */
    public function getSeason()
    {
        return $this->season;
    }

    /**
     * Generated from protobuf field <code>string season = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setSeason($var)
    {
        GPBUtil::checkString($var, True);
        $this->season = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string character = 40;</code>
     * @return string
     */
    public function getCharacter()
    {
        return $this->character;
    }

    /**
     * Generated from protobuf field <code>string character = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setCharacter($var)
    {
        GPBUtil::checkString($var, True);
        $this->character = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actor = 50;</code>
     * @return string
     */
    public function getActor()
    {
        return $this->actor;
    }

    /**
     * Generated from protobuf field <code>string actor = 50;</code>
     * @param string $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkString($var, True);
        $this->actor = $var;

        return $this;
    }

}

