<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kaamelott.proto

namespace Kaamelott;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kaamelott.Quote</code>
 */
class Quote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     */
    protected $quote = '';
    /**
     * Generated from protobuf field <code>.kaamelott.QuoteInfos infos = 20;</code>
     */
    protected $infos = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $quote
     *     @type \Kaamelott\QuoteInfos $infos
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kaamelott::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     * @return string
     */
    public function getQuote()
    {
        return $this->quote;
    }

    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setQuote($var)
    {
        GPBUtil::checkString($var, True);
        $this->quote = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kaamelott.QuoteInfos infos = 20;</code>
     * @return \Kaamelott\QuoteInfos
     */
    public function getInfos()
    {
        return $this->infos;
    }

    /**
     * Generated from protobuf field <code>.kaamelott.QuoteInfos infos = 20;</code>
     * @param \Kaamelott\QuoteInfos $var
     * @return $this
     */
    public function setInfos($var)
    {
        GPBUtil::checkMessage($var, \Kaamelott\QuoteInfos::class);
        $this->infos = $var;

        return $this;
    }

}

