<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kaamelott.proto

namespace Kaamelott;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kaamelott.RandomQuoteReply</code>
 */
class RandomQuoteReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     */
    protected $quote = '';
    /**
     * Generated from protobuf field <code>string author = 20;</code>
     */
    protected $author = '';
    /**
     * Generated from protobuf field <code>string character = 30;</code>
     */
    protected $character = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $quote
     *     @type string $author
     *     @type string $character
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kaamelott::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     * @return string
     */
    public function getQuote()
    {
        return $this->quote;
    }

    /**
     * Generated from protobuf field <code>string quote = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setQuote($var)
    {
        GPBUtil::checkString($var, True);
        $this->quote = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author = 20;</code>
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Generated from protobuf field <code>string author = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string character = 30;</code>
     * @return string
     */
    public function getCharacter()
    {
        return $this->character;
    }

    /**
     * Generated from protobuf field <code>string character = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setCharacter($var)
    {
        GPBUtil::checkString($var, True);
        $this->character = $var;

        return $this;
    }

}

